### ISSUE TITLE
Vertaisarvio RSA-salaus_tiralabra -projektille

### ISSUE THREAD

**Issue by bgran** [ItsTuukka/RSA-salaus_tiralabra#1]
## Viimeisin git pull: Sat  4 Dec 21:13:54 EET 2021

# Arvioinnit

1. Sovelluksen repositoryssä on paljon turhaa tavaraa joiden pitäisi mennä pois .gitignore -tiedoston ohessa. Ohjeet löytyvät tiralabra -projektin sivuilta. Ohessa omassa projektissa käytetty .gitignore:
% cat .gitignore 
\_\_pycache\_\_/
*.py[cod]
*.so
.Python
build/
Myös poetry.lock -tiedosto projektin pohjahakemistossaon turha.
2. Koodi eroteltu hieman ihmeellisesti. Eli jos sovellus -logiikan tulee tehdä jotain asioita kuten kirjastomaisia tehtäviä voisi sovellus/ -hakemistoon lisätä ohjelmat kuten
   2.1. Avaimen luontiin ohjelma.
   2.2. Viestin salaukseen ohjelma.
   2.3. Viestin salauksen purkamiseen ohjelma.
Nyt voi tehdä soveullus/ -hakemistoon kirjastotoiminnallisuuden kuten RSA -avainten generointi ja niin edelleen.
3. index.py -tiedosto toimii ilmeisesti pohjana sovelluskelle eli se tekee avainparin ja salaa avaimella viestin? Tätä ei kuitenkaan ole vielä toteutettu?
4. sovellus/src/sovelluslogiikka. Hyvin eritelty logiikkaa erikseen eri moduuleihin.
5. sovellus/src/sovelluslogiikka/generate_keys.py
  - Luokan nimi voisi olla Key_generator tai Key_Generator eli yleensä luokan nimi annetaan isoilla kirjaimilla nimen alussa.
  - \_\_init\_\_ -metoodissa voisi selittää hieman että mitä dataa se ottaa vastaan? Mikä on esim. rsa_key -argumentin funktio jos luokka on olemassa sitä varten että luodaan avainpari?
  - Omaan koodaussilmään osui siis self.rsa_key -luokan sitominen key_generator -luokan instanssin attribuuttiin. Olisiko helpompi tehdä vain instanssi luokasta ja käsitelllä sitä sellaisenaan. Ehkä taustalla on suunittelmallisuutta että voidaan antaa eri luokkia eri toiminnoille tai jotain vastaavaa?
  - Koodia voisi vähän piilottaa key_generator -luokassa esim.
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def is_prime(self):
     voisi olla:
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def __is_prime(self)
     missä metoodin alkupään viivat tekevät siitä vähän C++:n
     private -määrittelyn mukaista jälkeä.
     Eli sisäiset metoodit piilotetaan luokan käyttäjältä. Eli
     vain key_generator.generate_keys() -metoodi on julkaistu.

**Comment by ItsTuukka** [comment]
Kiitos vertaispalautteesta!
Nimeäminen on mennyt ihan ajattelemattomasti mennyt snake_case tyylillä, kiitos huomautuksesta se on nyt korjattu. Halusin myös kommentoida tuohon luokan sitomisen. Minulla on ollut ongelmia pythonissa importtien kanssa, varsinkin testejä tehdessä (no module named...) ja tuo kun sidon luokkia toisen luokan instanssiin on korjannut kaikki ongelmat. En ole tähän vielä parempaa ratkaisua löytänyt (vaikka kyllä tarkistanut monta kertaa että sellainen moduuli löytyy ja se on ihan oikein importattu).
Kiitoksia vielä palautteesta

**Comment by bgran** [comment]
Moi. Kommenttoin sen verran että tuo importtaaminen saattaa johtua hakemistosta puuttuvasta \_\_init\_\_.py -tiedostosta? En tiedä onko tämä ongelma tässä suhteessa mutta tulin vain ajatelleeksi asiaa.
